services:
  mongo:
    container_name: mongo
    image: mongo:8.0-rc-noble
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: taskFlowTest
volumes:
  mongodb_data:
